format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$cmd_duration\
$line_break\
$character"""

right_format = """$time"""

[username]
style_user = "bold green"
show_always = false

[hostname]
ssh_only = true
style = "bold green"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold blue"

[git_branch]
style = "bold green"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "bold yellow"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "🐍 "

[nodejs]
format = "[$symbol($version )]($style)"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
style = "dimmed white"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
