add_newline = false

format = """
[](fg:#444444)\
$username\
$hostname\
$directory\
[](fg:#444444) \
$character"""

right_format = """
$cmd_duration\
$python\
$nodejs\
[](fg:#444444)\
$git_branch\
$git_status\
$time\
"""

[username]
show_always = false
style_user = "fg:white bg:#444444 bold"
format = '[ $user]($style)'

[hostname]
ssh_only = true
style = "fg:white bg:#444444 bold"
format = '[@$hostname]($style)'

[directory]
truncation_length = 1
truncate_to_repo = false
style = "fg:bright-blue bg:#444444 bold"
format = '[ $path ]($style)'

[git_branch]
style = "fg:green bg:#444444 bold"
symbol = ""
format = '[ $branch(:$remote_branch)]($style)'
truncation_length = 11
truncation_symbol = "…"

[git_status]
style = "fg:yellow bg:#444444 bold"
format = '([ $all_status$ahead_behind]($style))'

[python]
format = '[\($virtualenv\)](bold yellow) '
detect_extensions = []
detect_files = []
detect_folders = []

[nodejs]
format = "[$symbol$version](bold green) "

[cmd_duration]
min_time = 2000
format = "[$duration](bold yellow) "

[time]
disabled = false
format = '[ $time ]($style)'
time_format = "%H:%M:%S"
style = "fg:#808080 bg:#444444"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
