set-option -g set-titles on
set -g status off
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'

bind-key j  select-pane -U
bind-key k  select-pane -D
bind-key h  select-pane -L
bind-key l  select-pane -R
bind-key m last-window
bind-key N previous-window

set -g mouse off

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
unbind p
bind p paste-buffer


bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

unbind [
bind Escape copy-mode

set-option -g history-limit 50000

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
